create table public.listings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  type text not null check (type in ('venda', 'aluguel', 'terreno')),
  status text not null default 'Disponível',
  price text not null,
  bedrooms integer not null default 0,
  bathrooms integer not null default 0,
  area integer not null,
  neighborhood text not null,
  address text not null,
  description text not null,
  image text,
  advertiser text not null,
  phone text not null,
  latitude double precision not null,
  longitude double precision not null,
  created_at timestamptz not null default now()
);

alter table public.listings enable row level security;

create policy "Anyone can read published listings"
on public.listings for select
using (true);

create policy "Users can create their own listings"
on public.listings for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own listings"
on public.listings for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own listings"
on public.listings for delete
to authenticated
using (auth.uid() = user_id);
