create table if not exists public.neighborhoods (
  name text primary key check (name = btrim(name) and char_length(name) > 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create or replace function public.normalize_neighborhood_name(value text)
returns text
language sql
immutable
strict
parallel safe
set search_path = pg_catalog
as $$
  select translate(
    lower(regexp_replace(btrim(value), '[[:space:]]+', ' ', 'g')),
    'áàâãäåéèêëíìîïóòôõöúùûüçñýÿ',
    'aaaaaaeeeeiiiiooooouuuucnyy'
  );
$$;

create unique index if not exists neighborhoods_normalized_name_uidx
  on public.neighborhoods (public.normalize_neighborhood_name(name));

insert into public.neighborhoods (name)
values
  ('Centro'),
  ('Jardim das Flores'),
  ('Jardim Primavera'),
  ('Residencial Santana'),
  ('Vila Nova'),
  ('Zona Norte')
on conflict do nothing;

create table public.listings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  type text not null check (type in ('venda', 'aluguel', 'terreno', 'ponto_comercial')),
  property_category text not null default 'casa' check (property_category in ('casa', 'apartamento', 'terreno', 'ponto_comercial')),
  purpose text not null default 'venda' check (purpose in ('venda', 'aluguel')),
  status text not null default 'em_analise' check (status in ('em_analise', 'aprovado', 'reprovado', 'concluido')),
  destaque_home boolean not null default false,
  ordem_destaque integer,
  constraint listings_featured_order_check check (
    (destaque_home and ordem_destaque is not null and ordem_destaque > 0)
    or (not destaque_home and ordem_destaque is null)
  ),
  motivo_reprovacao text,
  price text not null,
  bedrooms integer not null default 0,
  bathrooms integer not null default 0,
  area integer not null,
  city text not null default 'Ipuã-SP',
  cep text,
  number text,
  street text,
  neighborhood text not null references public.neighborhoods(name) on update cascade on delete restrict,
  address text not null,
  description text not null,
  image text,
  images jsonb not null default '[]'::jsonb,
  advertiser text not null,
  phone text not null,
  latitude double precision not null,
  longitude double precision not null,
  created_at timestamptz not null default now()
);

alter table public.listings enable row level security;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated, anon;

alter table public.neighborhoods enable row level security;

drop policy if exists "Anyone can view active neighborhoods" on public.neighborhoods;
create policy "Anyone can view active neighborhoods"
on public.neighborhoods for select
using (active or public.is_admin());

drop policy if exists "Admins can create neighborhoods" on public.neighborhoods;
create policy "Admins can create neighborhoods"
on public.neighborhoods for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update neighborhoods" on public.neighborhoods;
create policy "Admins can update neighborhoods"
on public.neighborhoods for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete neighborhoods" on public.neighborhoods;
create policy "Admins can delete neighborhoods"
on public.neighborhoods for delete
to authenticated
using (public.is_admin());

grant select on public.neighborhoods to anon, authenticated;
grant insert, update, delete on public.neighborhoods to authenticated;

drop policy if exists "Users can view their admin record" on public.admin_users;
create policy "Users can view their admin record"
on public.admin_users for select
to authenticated
using (auth.uid() = user_id);

create policy "Anyone can read published listings"
on public.listings for select
using (status = 'aprovado' or auth.uid() = user_id or public.is_admin());

create policy "Users can create their own listings"
on public.listings for insert
to authenticated
with check (auth.uid() = user_id and status = 'em_analise');

create policy "Users can update their own listings"
on public.listings for update
to authenticated
using (auth.uid() = user_id or public.is_admin())
with check (public.is_admin() or (auth.uid() = user_id and status in ('em_analise', 'concluido')));

create policy "Users can delete their own listings"
on public.listings for delete
to authenticated
using (auth.uid() = user_id or public.is_admin());

create or replace function public.require_active_listing_neighborhood()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' and new.neighborhood is not distinct from old.neighborhood then
    return new;
  end if;

  if not exists (
    select 1
    from public.neighborhoods
    where name = new.neighborhood
      and active
  ) then
    raise exception 'O bairro selecionado não está cadastrado ou está inativo.'
      using errcode = '23514';
  end if;

  return new;
end;
$$;

drop trigger if exists listings_require_active_neighborhood on public.listings;
create trigger listings_require_active_neighborhood
before insert or update on public.listings
for each row execute function public.require_active_listing_neighborhood();
